# Project information
site_name: stackover_flow_text_classification_dvc
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Data-prep-stage: data_prep.md
  - Featurization: featurization.md

site_author: siddharth modi
site_description: >-
  DESCRIPTION

# Repository
repo_name: siddmodi/stackover_flow_text_classification
repo_url: https://github.com/siddmodi/stackover_flow_text_classification

# Configuration
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/siddmodi

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/siddharth-modi-81b868172/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/siddmodi"  target="_blank" rel="noopener">Siddharth modi</a>